# Generated by Django 4.2.11 on 2024-07-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_cart_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColourCoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin', models.TextField(max_length=100)),
                ('colour1', models.TextField(max_length=100)),
                ('colour2', models.TextField(max_length=100)),
                ('colour3', models.TextField(max_length=100)),
                ('colour4', models.TextField(max_length=100)),
            ],
        ),
    ]
