# Generated by Django 4.2.11 on 2024-07-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_outfit_recipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professionals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('username', models.TextField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='outfit',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
