# Generated by Django 4.2.11 on 2024-07-14 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_professionals_alter_outfit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_outfits', to='store.professionals'),
        ),
    ]
